ALTER TABLE drivers ADD COLUMN IF NOT EXISTS lat NUMERIC(9,6) DEFAULT NULL;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS lng NUMERIC(9,6) DEFAULT NULL;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS location_updated_at TIMESTAMP DEFAULT NULL;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS from_lat NUMERIC(9,6) DEFAULT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS from_lng NUMERIC(9,6) DEFAULT NULL;